# Generated by Django 5.2.6 on 2025-09-09 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movieinfo',
            old_name='description',
            new_name='summary',
        ),
    ]
